{% set name = "parsel" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aff28e68c9b3f1a901db2a4e3f158d8480a38724d7328ee751c1a4e1c1801e39

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37]

requirements:
  host:
    - python
    - pip
    - pytest-runner 6.0.0
    - setuptools
    - wheel
  run:
    - python
    # https://github.com/scrapy/parsel/pull/277
    - cssselect >=1.2.0
    - jmespath
    - lxml
    - packaging
    - w3lib >=1.19.0

test:
  source_files:
    - tests
  imports:
    - parsel
  requires:
    - pip
    - pytest
  commands:
    - pip check
    # Tests failed on all platforms. 
    # Probably due to this constraint https://github.com/scrapy/parsel/blob/f5f73d34ba787ad0c9df25de295de6e196ecd91d/tests/requirements.txt#L1. 
    # We haven't psutil 5.6.3 on defaults
    - py.test -v -k "not (test_differences_parsing_xml_vs_html or test_nested_selectors or test_re or test_replacement_null_char_from_body or test_select_on_text_nodes or test_selector_get_alias or test_selector_getall_alias or test_selector_over_text or test_selectorlist_get_alias or test_selectorlist_getall_alias or test_slicing or test_text_pseudo_element)" tests

about:
  home: https://github.com/scrapy/parsel
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: library to extract data from HTML and XML using XPath and CSS selectors
  description: |
    Features of parcel are, Extract text using CSS or XPath selectors and
    Regular expression helper methods.
  dev_url: https://github.com/scrapy/parsel
  doc_url: https://parsel.readthedocs.io/en/latest/
  doc_source_url: https://github.com/scrapy/parsel/blob/master/docs/index.rst
